"""models cleanup

Revision ID: 0f44ab004d0d
Revises: 201e783c2508
Create Date: 2026-02-13 14:46:35.269697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f44ab004d0d'
down_revision = '201e783c2508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('is_paid', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_is_paid'), ['is_paid'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_person_id'), ['person_id'], unique=False)

    op.create_table('invoice_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('load_entry_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['load_entry_id'], ['load_entry.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_item_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_item_load_entry_id'), ['load_entry_id'], unique=False)

    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('billing_price', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_price_flugplatz_id'), ['flugplatz_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_price_period_id'), ['period_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_price_status_code'), ['status_code'], unique=False)

    with op.batch_alter_table('billing_price_period', schema=None) as batch_op:
        batch_op.alter_column('is_homebase_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('flight_operation_period', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_flight_operation_period_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_flight_operation_period_flugplatz_id'), ['flugplatz_id'], unique=False)

    with op.batch_alter_table('load', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_load_aircraft_id'), ['aircraft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_load_airfield_id'), ['airfield_id'], unique=False)

    with op.batch_alter_table('load_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('status_code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('is_teacher',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_video',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('gear_rental',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('billed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('paid',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_load_entry_billed'), ['billed'], unique=False)
        batch_op.create_index(batch_op.f('ix_load_entry_load_id'), ['load_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_load_entry_paid'), ['paid'], unique=False)
        batch_op.create_index(batch_op.f('ix_load_entry_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_load_entry_status_code'), ['status_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_load_entry_status_definition_id'), ['status_definition_id'], unique=False)

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('is_member',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('status_key',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('is_tandem_guest',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('emergency_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('emergency_phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_person_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_iban'), ['iban'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_phone'), ['phone'], unique=False)

    with op.batch_alter_table('pricing', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('included_in_course',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_pricing_height_m'), ['height_m'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricing_status_key'), ['status_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricing_status_label'), ['status_label'], unique=False)
        batch_op.create_unique_constraint('uq_pricing_status_height', ['status_key', 'height_m'])

    with op.batch_alter_table('status_definitions', schema=None) as batch_op:
        batch_op.alter_column('preis_1500',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('preis_3000',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('preis_4000',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_status_definitions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_status_definitions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_definitions_label'), ['label'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_definitions_sort_order'), ['sort_order'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_definitions_sort_order'))
        batch_op.drop_index(batch_op.f('ix_status_definitions_label'))
        batch_op.drop_index(batch_op.f('ix_status_definitions_is_active'))
        batch_op.drop_index(batch_op.f('ix_status_definitions_code'))
        batch_op.alter_column('preis_4000',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('preis_3000',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('preis_1500',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('pricing', schema=None) as batch_op:
        batch_op.drop_constraint('uq_pricing_status_height', type_='unique')
        batch_op.drop_index(batch_op.f('ix_pricing_status_label'))
        batch_op.drop_index(batch_op.f('ix_pricing_status_key'))
        batch_op.drop_index(batch_op.f('ix_pricing_height_m'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('included_in_course',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_phone'))
        batch_op.drop_index(batch_op.f('ix_person_last_name'))
        batch_op.drop_index(batch_op.f('ix_person_iban'))
        batch_op.drop_index(batch_op.f('ix_person_first_name'))
        batch_op.drop_index(batch_op.f('ix_person_email'))
        batch_op.alter_column('emergency_phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('emergency_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('is_tandem_guest',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('status_key',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('is_member',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('load_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_load_entry_status_definition_id'))
        batch_op.drop_index(batch_op.f('ix_load_entry_status_code'))
        batch_op.drop_index(batch_op.f('ix_load_entry_person_id'))
        batch_op.drop_index(batch_op.f('ix_load_entry_paid'))
        batch_op.drop_index(batch_op.f('ix_load_entry_load_id'))
        batch_op.drop_index(batch_op.f('ix_load_entry_billed'))
        batch_op.alter_column('paid',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('billed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('gear_rental',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_video',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_teacher',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('status_code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('paid_at')
        batch_op.drop_column('billed_at')

    with op.batch_alter_table('load', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_load_airfield_id'))
        batch_op.drop_index(batch_op.f('ix_load_aircraft_id'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('flight_operation_period', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flight_operation_period_flugplatz_id'))
        batch_op.drop_index(batch_op.f('ix_flight_operation_period_date'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('billing_price_period', schema=None) as batch_op:
        batch_op.alter_column('is_homebase_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('billing_price', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_price_status_code'))
        batch_op.drop_index(batch_op.f('ix_billing_price_period_id'))
        batch_op.drop_index(batch_op.f('ix_billing_price_flugplatz_id'))

    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_item_load_entry_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_item_invoice_id'))

    op.drop_table('invoice_item')
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_person_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_is_paid'))

    op.drop_table('invoice')
    # ### end Alembic commands ###
