"""add billing price tables

Revision ID: 201e783c2508
Revises: 03b172b144dd
Create Date: 2026-02-13 03:06:11.276678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201e783c2508'
down_revision = '03b172b144dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('street', sa.String(length=200), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=200), nullable=False),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('vat_id', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('logo_filename', sa.String(length=200), nullable=True),
    sa.Column('canopy_rent_member_eur', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('canopy_rent_member_cap_eur', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('canopy_rent_guest_eur', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('canopy_rent_guest_cap_eur', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_price_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('orga_fee_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_homebase_default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flugplatz_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.String(length=50), nullable=False),
    sa.Column('height_m', sa.Integer(), nullable=False),
    sa.Column('price_eur', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['flugplatz_id'], ['flugplatz.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['billing_price_period.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flugplatz_id', 'period_id', 'status_code', 'height_m', name='uq_price_flightperiod_status_height')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing_price')
    op.drop_table('billing_price_period')
    op.drop_table('billing_config')
    # ### end Alembic commands ###
