"""Add default_height to aircraft

Revision ID: 71bde9ba21f0
Revises: cf1a139bc1c4
Create Date: 2026-02-18 01:15:21.973629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71bde9ba21f0'
down_revision = 'cf1a139bc1c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pricing_height_m'))
        batch_op.drop_index(batch_op.f('ix_pricing_status_key'))
        batch_op.drop_index(batch_op.f('ix_pricing_status_label'))

    op.drop_table('pricing')
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_height', sa.Integer(), server_default='3000', nullable=False))

    with op.batch_alter_table('flugplatz', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('load', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_load_load_number'), ['load_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('load', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_load_load_number'))

    with op.batch_alter_table('flugplatz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.drop_column('default_height')

    op.create_table('pricing',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('status_key', sa.VARCHAR(length=50), nullable=False),
    sa.Column('status_label', sa.VARCHAR(length=100), nullable=False),
    sa.Column('height_m', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0'"), nullable=False),
    sa.Column('included_in_course', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_key', 'height_m', name=op.f('uq_pricing_status_height'))
    )
    with op.batch_alter_table('pricing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pricing_status_label'), ['status_label'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricing_status_key'), ['status_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricing_height_m'), ['height_m'], unique=False)

    # ### end Alembic commands ###
