"""add soft delete to person

Revision ID: cf1a139bc1c4
Revises: 0fbbe3921349
Create Date: 2026-02-17 00:49:51.668892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf1a139bc1c4'
down_revision = '0fbbe3921349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_reason', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_person_deleted_at'), ['deleted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_deleted_at'))
        batch_op.drop_column('deleted_reason')
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
