# app/routes/navigation.py

NAV_ITEMS = [
    {
        "id": "loads",
        "label": "Loads",
        "endpoint": "load.list_loads",
        "icon_type": "include",
        "icon_value": "icons/parachute.svg",
        "admin_only": False,
    },
    {
        "id": "flugzeuge",
        "label": "Flugzeuge",
        "endpoint": "aircraft.list_aircraft",
        "icon_type": "bi",
        "icon_value": "airplane",
        "admin_only": False,
    },
    {
        "id": "flugplaetze",
        "label": "Flugplätze",
        "endpoint": "flugplatz.list_flugplaetze",
        "icon_type": "bi",
        "icon_value": "geo-alt",
        "admin_only": False,
    },
    {
        "id": "personen",
        "label": "Personen",
        "endpoint": "person.list_persons",
        "icon_type": "bi",
        "icon_value": "people",
        "admin_only": False,
    },
    {
        "id": "abrechnung",
        "label": "Abrechnung",
        "endpoint": "billing.overview",
        "icon_type": "bi",
        "icon_value": "calculator",
        "admin_only": False,
    },
    {
        "id": "statistik",
        "label": "Statistik",
        "endpoint": "load.statistics_view",
        "icon_type": "bi",
        "icon_value": "bar-chart",
        "admin_only": False,
    },
    {
        "id": "display",
        "label": "Display",
        "url": "/loads/display",
        "icon_type": "bi",
        "icon_value": "display",
        "target": "_blank",
        "admin_only": False,
    },
    {
        "id": "display_landscape",
        "label": "Display quer",
        "url": "/loads/display?landscape=1",
        "icon_type": "bi",
        "icon_value": "display",
        "target": "_blank",
        "admin_only": False,
    },
    {
        "id": "logout",
        "label": "Logout",
        "endpoint": "admin_auth.admin_logout",
        "icon_type": "bi",
        "icon_value": "door-open",
        "admin_only": True,
        "tile_class": "tile-danger",
    },
]